CodingTrain/thecodingtrain.com

- content/pages/homepage/index.json
- src/components/Footer.js
- src/pages/index.js
- Changes "Go now" button message in Passenger Showcase Highlight section to "Check out showcase highlight"
- Changes "Check out now" message in Passenger Showcase Highlight section to "Do you want to see other people's work?"
- Changes "Go" button message in event information to "go to event"
- Changes "We’ve created a simple guide to help you get started" to "Don't know where to start?"  in New to Coding? section
- Changes "guide the ride" button message to "read getting started guide"  in New to Coding? section
- Changes "have questions? our community is here to help" to "have questions?"  in New to Coding? section
- Changes "join discord" button message to "join community discord"  in New to Coding? section
- Adds descriptions to "join" buttons in Support section
- Changes links in …
> Improved URL descriptions in homepage

- content/videos/challenges/15-object-oriented-fractal-trees/index.json
> Adding Description to Coding Challenge: OOP Fractal Tree

- content/pages/about/index.json
- node-scripts/page-generation.js
- src/components/ChallengesPanel.js
- src/components/PassengerShowcasePanel.js
- src/components/challenges/Card.js
- src/pages/index.js
- src/pages/routes.js
- src/templates/challenge.js
- src/templates/challenges.js
Fix to #169. I also linked to passenger showcase guide in the videos showcase panel
> Plural challenges paths

- content/videos/challenges/145-ray-casting-2d/index.json
- content/videos/challenges/146-rendering-ray-casting/index.json
Fixing titles on code examples, links, and adding emojis
> Ray casting

- content/pages/guides/getting-started.md
@elizabethslash and I are going over this right now!
> trivial change to demo preview build

- src/components/TopBar.js
> Fix date ordinal numbers for special case

- content/pages/about/index.json
- node-scripts/schema.js
- src/pages/about.js
- src/styles/pages/about.module.css
@fdoflorenzano would it be possible to have an additional property for each person, so instead of:
```json
{
"name": "Editing and Video Production: Mathieu Blanchette",
"url": "https://mathieu.com"
},
```
We'd have:
```json
{
"name": "Mathieu Blanchette",
"url": "https://mathieu.com",
"role": "Editing and Video Production"
},
```
Then the layout could look more like the following (with the url only linking to the name?)
> Acknowledgements

- content/pages/homepage/index.json
I am going to show a screenshot of the homepage in the CT "wave function collapse" video premiering this Saturday so making some edits to the homepage language.
> Homepage Edits

- content/videos/challenges/171-wave-function-collapse/index.json
> WFC Timestamps and Links

- content/videos/challenges/171-wave-function-collapse/index.json
Fixed some missing/irrelevant links.
You might also want to update the description (timestamps and links): (also added gh repo link ~~which isn't added by the script~~)
```
Straight out of quantum mechanics, Wave Function Collapse is an algorithm for procedural generation of images. In this video (recorded over 3 live streams) I attempt the tiled model and explore a variety of solutions to the algorithm in JavaScript with p5.js. https://thecodingtrain.com/challenges/171-wave-function-collapse
💻 Github Repo: https://github.com/CodingTrain/Wave-Function-Collapse
🕹️ p5.js Web Editor Sketch: https://editor.p5js.org/codingtrain/sketches/_kbz6Xq7l
🎥 Previous video: https://www.youtube.com/watch?v=0zac-cDzJwA&list=PLRqwX-V7Uu6ZiZxtDDRCi6uhfTH4FilpH
🎥 All videos: …
```
> Fixes to WFC Video Metadata

- content/pages/challenges/index.json
Changing the featured challenge to WFC!
> Featuring WFC

- redirects.json
This request requires #344 before merging
> add common redirects

- content/videos/challenges/90-dithering/index.json
Discovered during discussion of #350
> Fixing Error in Dithering Challenge JSON

- src/components/CodeExampleList.js
- src/components/VideoInfo.js
- src/templates/challenge.js
This PR closes #400.
(Merge after #402 for tests)
> Use index image as default for code examples 

- content/videos/challenges/c3-hilbert-curve/showcase/contribution10.json
- content/videos/challenges/c3-hilbert-curve/showcase/contribution11.json
- content/videos/challenges/c3-hilbert-curve/showcase/contribution8.json
Sorry!!  I missed  the links for these contributions.
> Fixing link to contributions

- node-scripts/node-generation.js
> fix: showcase covers for videos are now correclty linked

- node-scripts/node-generation.js
> fix: update code example cover image linking

- content/pages/guides/maintain-website-guide.md
I have updated the guide to include information about the new index image format.  I have left this as a optional step, and am willing to continue to redo them.
> Maintaining the website--updating information about index images

- content/videos/challenges/70-nearest-neighbors-recommendation-engine/index.json
@kfahn22 note that the property `github` is not valid. We can use `other` for anything that is not p5 or Processing. However, I think it's simpler just to link to the p5 editor sketch here when we have it.
> Fix for coding challenge 70

- src/components/Footer.module.css
- src/components/challenges/PartsTimeline.module.css
- src/components/tracks/OverviewTimeline.module.css
- src/styles/pages/index.module.css
I noticed 3 minor UI problems when viewing the website on my phone :
- On the Homepage, a horizontal scrollbar appears on a certain screen width, due to : 
- (A) An overflow in the "CHALLENGES" `.subheader`
- (B) An overflow in the footer `.navBox`
- (C) On the Tracks and Challenge parts timelines, the line which goes through seen videos appears empty on some screen densities or zoom level
I fixed these details using CSS.
(A) Before : a horizontal scrollbar appears and on the smallest size, the text is slightly off-centered 
(A) After : I made the "getting started" title wrap lines and fixed the center alignment on the smallest size
(B) Before
(B) After : I used an `overflow: hidden` to fix this (it was already applied but only on smaller screen sizes)
(C) Before (zoom level 175%)
(C) …
> Fix minor UI problems on small screens

- netlify/functions/submission-background.js
This PR adds improvements to showcase PR creation as proposed in #512.
- Add preview image in PR body
- Add showcase label to PR
Preview URL for testing: https://deploy-preview-516--codingtrain.netlify.app/guides/passenger-showcase-guide
Preview PR: #522
> Showcase Submission PR Enhancements

- content/pages/homepage/index.json
- node-scripts/page-generation.js
Just some misc small updates and changes to the site. The one large item here is changing the pagination from 10 per page to 50. Challenges are now 2 pages (but will grow to 4 and beyond) and tracks are just one. I could consider 100 per page but maybe that's going too far.
> Misc Updates and Edits

- content-testing/file-formats.js
- content/videos/code/1-intro/1-intro/index.json
- node-scripts/yt-description.js
> Adding Nebula Slug to Video JSON

- node-scripts/yt-description.js
- Added hashtags based on topics and tags
- Allow usage of full file path along with website URL
```
Usage:
npm run yt-desc
npm run yt-desc https://thecodingtrain.com/path/to/video/page
npm run yt-desc ./path/to/index.json
```
> yt-desc: Add hashtags to description

- README.md
Hi! I updated the readme to include the link to thecodingtrain.com website.
This is my first ever github pull request :)
> updated text to link for website

- src/components/PassengerShowcaseForm.js
- src/components/PassengerShowcaseForm.module.css
Hey, I added missing hover state to the submit button. 
I like The Coding Train channel on Youtube. Thank you for the many useful videos and articles. :) Have a nice day!
> Added hover state to the PassengerShowCaseForm's button

- content/videos/code/7-arrays/4-mouse-interaction/index.json
- content/videos/code/7-arrays/upload-editor/index.json
> adding links in youtube description

- redirects.json
Adding these after reviewing the site's logs. Only one missing is Fluid Simulation as referenced in #558
> Additional Redirects

- content/videos/challenges/174-graphics-applesoft-basic/index.json
https://nebula.tv/videos/codingtrain-coding-challenge-174-fractal-tree-on-apple-ii
> Adding Nebula extended cut

- redirects.json
Forgot I show this URL in the video!
> Redirect for Apple 2 Fractal video

- src/components/ChallengesPanel.js
Hey! I just noticed that I introduced a small bug when doing the final touches on PR #572. The spacer shouldn't appear on the right :sweat_smile: 
So here's the fix :smile:
> Fix small bug on the spacer of related challenges

- src/components/PassengerShowcasePanel.js
- src/components/PassengerShowcasePanel.module.css
- src/utils/index.js
:steam_locomotive: This PR implements one part of issue #590
Preview example:
- Challenge: https://deploy-preview-593--codingtrain.netlify.app/challenges/173-snake-applesoft-basic
- Track video: https://deploy-preview-593--codingtrain.netlify.app/tracks/code-programming-with-p5-js/code/3-conditionals/1-conditionals
Placeholder visible when client code is loading (here on a simulated slow connection) :
> Shuffled Passenger Showcase on Video Page

- content/pages/homepage/index.json
- src/components/ChallengesPanel.js
- src/components/PassengerShowcasePanel.js
- src/hooks/index.js
- src/pages/index.js
- src/styles/pages/index.module.css
- src/utils/index.js
This PR addresses one part of issue #590 : randomizing the featured challenges that appear on the homepage of the website.
Placeholder visible when client code is loading (here on a simulated slow connection) :
Preview : https://deploy-preview-600--codingtrain.netlify.app
> Three random Featured Challenges on the Homepage

- content/videos/challenges/173-snake-applesoft-basic/showcase/contribution-1664316625.json
Just fixing an annoying detail:
> Replacing unknown character by "ç".

- content/pages/homepage/index.json
- node-scripts/node-generation.js
- node-scripts/schema.js
- src/pages/index.js
- src/styles/pages/index.module.css
- src/utils/index.js
This PR implements a part of issue #590 :steam_locomotive: 
This is a work in progress :building_construction: 
Preview : https://deploy-preview-606--codingtrain.netlify.app/
Loading on a simulated slow connection :
> Random featured Passenger Showcase on the Homepage

- redirects.json
Someone on the discord had an issue where the link found [here](https://www.youtube.com/watch?v=0L2n8Tg2FwI) was broken so I added it
I hope this is the correct file to edit
> Add coding challenge 90

- README.md
Added a temporary short note about hacktoberfest in README, as discussed in #611 
@kfahn22 if you think there is more to add or to change, please feel free to do a review!
> Added note about hacktoberfest in README

- content/videos/challenges/1-starfield/index.json
- content/videos/challenges/10-dfs-maze-generator/index.json
- content/videos/challenges/11-3d-terrain-generation-with-perlin-noise/index.json
- content/videos/challenges/125-fourier-series/index.json
- content/videos/challenges/133-time-tables-cardioid-visualization/index.json
- content/videos/challenges/153-interactive-drawing-with-sketchrnn/index.json
- content/videos/challenges/19-superellipse/index.json
- content/videos/challenges/2-menger-sponge/index.json
- content/videos/challenges/20-3d-cloth-simulation/index.json
- content/videos/challenges/23-2d-supershapes/index.json
- content/videos/challenges/24-perlin-noise-flow-field/index.json
- content/videos/challenges/25-spherical-geometry/index.json
- content/videos/challenges/26-3d-supershapes/index.json
- content/videos/challenges/28-metaballs/index.json
- content/videos/challenges/29-smart-rockets-in-p5js/index.json
- content/videos/challenges/3-snake-game/index.json
- content/videos/challenges/4-purple-rain/index.json
- content/videos/challenges/5-space-invaders/index.json
- content/videos/challenges/55-mathematical-rose-patterns/index.json
- content/videos/challenges/6-mitosis-simulation/index.json
- content/videos/challenges/90-dithering/index.json
- content/videos/challenges/c4-worley-noise/index.json
- content/videos/challenges/c5-marching-squares/index.json
This pull request adds related challenges, updates some code links that went to the archived repo, and adds timestamps for 90-dithering.
> Adding related challenges 

- src/components/PassengerShowcaseForm.js
We don't have the ability to provide a specific error message but this will at least be a little friendlier and provide contact information to get help.
> New Showcase submission error message

- src/components/ButtonPanel.module.css
- src/components/GuideCard.module.css
- src/components/PagePanel.module.css
- src/components/challenges/VideoSection.module.css
- src/components/tracks/VideoSection.module.css
- src/styles/pages/index.module.css
Choo choo! :steam_locomotive:  I fixed a very small 1px height difference on the ButtonPanel component and reviewed every usage of this component to make sure everything stays perfectly aligned :straight_ruler: (Am I really obsessing over 1px? Yes :upside_down_face:)
Here's the before and after (you'll probably have to squint a little to see the difference :smile:) :
**Challenge/Track video page**
> Pixel perfect adjustment on ButtonPanel

- content/videos/challenges/41-clappy-bird/index.json
> Clappy Bird fix merge conflict

- redirects.json
Noticing that this page is suddenly getting a lot of traffic so redirecting!
> Adding perlin noise terrain redirect

- content/videos/challenges/133-time-tables-cardioid-visualization/index.json
- content/videos/challenges/149-tic-tac-toe/index.json
- content/videos/challenges/154-tic-tac-toe-minimax/index.json
- content/videos/challenges/16-l-system-fractal-trees/index.json
- content/videos/challenges/163-bezier-curves/index.json
- content/videos/challenges/74-clock/index.json
- content/videos/challenges/77-recursion/index.json
133-time-table edited related challenges and added timecodes
154-tic-tac-toe edited related challenges and code example links
149-tic-tac-toe edited related challenges (adding other coding challenges with "beginner" topic)
163-bezier edited json to have same format as other challenges,  added related challenges, updated links
74-clock added timestamps and related challenges
Changed all beginner topic labels to "beginner" for consistency
Removed "beginner" topic from 16 (L-system) & 154, added to clock.
> Adding timecodes, relatedChallenges, editing topics and links

- content/videos/challenges/12-lorenz-attractor/index.json
- content/videos/challenges/13-reaction-diffusion/index.json
- content/videos/challenges/14-fractal-trees-recursive/index.json
- content/videos/challenges/15-object-oriented-fractal-trees/index.json
- content/videos/challenges/16-l-system-fractal-trees/index.json
- content/videos/challenges/17-fractal-trees-space-colonization/index.json
- content/videos/challenges/18-3d-fractal-trees/index.json
- content/videos/challenges/19-superellipse/index.json
- content/videos/challenges/24-perlin-noise-flow-field/index.json
This updates the json for 12, 13-19 to include the link to Kadenze class.  Also add link to Algorithmic botany track for 14-18.
> Update json to include link to Kadenze class 

- content/videos/challenges/25-spherical-geometry/index.json
- content/videos/challenges/26-3d-supershapes/index.json
- content/videos/challenges/29-smart-rockets-in-p5js/index.json
- content/videos/challenges/37-diastic-machine/index.json
- content/videos/challenges/51-a-pathfinding-algorithm/index.json
- content/videos/challenges/52-random-walker/index.json
- content/videos/challenges/53-random-walker-with-vectors-and-levy-flight/index.json
- content/videos/challenges/54-islamic-star-patterns/index.json
- content/videos/challenges/55-mathematical-rose-patterns/index.json
- content/videos/challenges/59-steering-behaviors/index.json
- content/videos/challenges/61-fractal-spirograph/index.json
- content/videos/challenges/62-plinko-with-matterjs/index.json
- content/videos/challenges/64-kinematics/index.json
- content/videos/challenges/69-evolutionary-steering-behaviors/index.json
-25, 26 (supershapes) changing links to supershape track 
-29-smart-rockets adding link to genetic algorithm playlist for 
-A* adding link to livestream archive and edited code example links, moved link for 10 to related challenges
-52, 53 random-walker adding link to 2018 class and NOC (from YT desc)
-54islamic-star - adding link to livestream archive
-55-mathematic-rose editing language field and code example links
-59-steering-behaviors add related challenges
-61-fractal-spirograph add link to livestream archive
62-plinko add related challenges
64-kinematics edit related challenges
69-evolutionary-steering-behavior edit related challenges, edited topic for consistency
> Update json to add links found in YT description

- node-scripts/yt-description.js
@dipamsen can you check this? cc @kfahn22
> YT Description Generator Bug Fix

- content/videos/challenges/163-bezier-curves/index.json
(not updating related challenges as it is claimed by @kfahn22 in the spreadsheet)
> fix typo in url

- content/pages/homepage/index.json
I used a random number generator to choose 7 new challenges (left two most recent).  I am not sure if you would prefer a more curated list?
> Add new featured challenges 

- content/tracks/side-tracks/games/index.json
I have put all of the videos in the Video Games playlist,  plus 115 and 174.
> Adding  Video Games track

- content/videos/challenges/36-blobby/index.json
- content/videos/challenges/39-madlibs-generator/index.json
- content/videos/challenges/54-islamic-star-patterns/index.json
- content/videos/challenges/64-kinematics/index.json
- content/videos/challenges/86-cube-wave-by-bees-and-bombs/index.json
- content/videos/challenges/87-3d-knots/index.json
- content/videos/challenges/89-langtons-ant/index.json
- content/videos/challenges/90-dithering/index.json
36-blobby add 32-agar.io to related challenges
39-add link to GitHub repo
54-add another group link category for charities
64-kinematics fix typo and add another link to livestream archive
86-bees and bombs add related challenge and link to livestream archive
87-3d knots add related challenge and link to livestream archive
89 langton's ant, 90-dithering add link to livestream archive
> Adding links to livestream archives, other links in yt-desc, related challenges, fix typos

- content/videos/challenges/108-barnsley-fern/index.json
- content/videos/challenges/2-menger-sponge/index.json
- content/videos/challenges/79-number-guessing-chatbot/index.json
A little PR
- Since CC 79 and 80 are like parts of the same challenge, I made their topic and language tags same
-  Changed group link titles of CC 108 and CC 002.
I don't think it needs to have the `hacktober-accepted` label.
> Some fixes

- content/tracks/side-tracks/games/index.json
> Removing multi-part challenges from games track

- redirects.json
> additional redirects based on traffic logs

- content/pages/homepage/index.json
- content/videos/challenges/c2-collatz-conjecture/showcase/contribution11.json
update featured challenges(again randomly chosen) and featured showcases
Updating name on one of the featured showcases
> Featured challenges/ showcase-10/30

- content/tracks/side-tracks/games/index.json
- src/components/tracks/OverviewTimeline.js
- src/components/tracks/VideoSection.js
- src/hooks/index.js
- src/templates/track-video.js
This fixes issue #738 :steam_locomotive: 
Preview: https://deploy-preview-743--codingtrain.netlify.app/tracks/games/46-asteroids
> Handle Multi-Part Challenges in Tracks

- CONTRIBUTING.md
- README.md
Another `hacktoberfest` is over. We recieved a lot of pull requests this year for this wonderful occasion and it has helped the repository immensely. Almost all of the coding challenges are now ported, and all of them are claimed. This was a very productive month. Thanks to everyone who contributed to thecodingtrain.com during `hacktoberfest`!
This pull request removes all the `hacktoberfest` help related stuff from `README` and `CONTRIBUTING`, and adds a more generalised introduction to the `CONTRIBUTING`. Looking forward to next year!
PS: I am removing all the `hacktoberfest` labels from issues. Noting that #611 can now be closed.
> Hacktoberfest Cleanup

- content/videos/challenges/109-visualizing-500000-subscribers/index.json
- content/videos/challenges/114-bubble-sort-visualization/index.json
- content/videos/challenges/116-lissajous-curve-table/index.json
- content/videos/challenges/33-poisson-disc-sampling/index.json
- content/videos/challenges/92-xor-problem/index.json
- content/videos/challenges/94-2048/index.json
- content/videos/challenges/97-book-of-pi/index.json
- content/videos/challenges/99-neural-network-color-predictor/index.json
Add relative challenges to 33, 92, 109, 114
Add/edit links to livestream archive 33, 92, 97, 99
33, 116 add links from yt-desc 
33 - fix typo
> add/edit  links to livestream archive, add relative challenges, fix typo

- content/videos/challenges/101-may-the-4th-scrolling-text/index.json
- content/videos/challenges/102-2d-water-ripple/index.json
- content/videos/challenges/111-animated-sprites/index.json
- content/videos/challenges/55-mathematical-rose-patterns/index.json
- content/videos/challenges/70-nearest-neighbors-recommendation-engine/index.json
- content/videos/challenges/72-frogger/index.json
- content/videos/challenges/86-cube-wave-by-bees-and-bombs/index.json
- content/videos/challenges/88-snowfall/index.json
- content/videos/challenges/c1-maurer-rose/index.json
- content/videos/challenges/c5-marching-squares/index.json
70, 101, 102 Fix typos
c1, 111 Add related challenges
72 frogger edit part titles, add link from yt-desc and link to livestream archive
86, 88 Add ts to livestream archive links
c1 add link in yt-desc
c5 - delete links for videos in related challenges
> Adding links to livestream archive + links from yt-desc, related challenges, fix typos

- content/videos/challenges/104-linear-regression-with-tensorflowjs/index.json
- content/videos/challenges/105-polynomial-regression-with-tensorflowjs/index.json
- content/videos/challenges/106-xor-problem-with-tensorflowjs/index.json
- content/videos/challenges/119-binary-to-decimal-conversion/index.json
104 add playlist from yt-desc 
104, 105, 119 add timestamp to livestream link 
106 add related challenges and link to livestream archive
> add related challenges and add/edit links to livestream archive

- content/videos/challenges/117-seven-segment-display/index.json
- content/videos/challenges/120-bit-shifting/index.json
- content/videos/challenges/127-brownian-tree-snowflake/index.json
- content/videos/challenges/128-sketch-rnn-snowflakes/index.json
- content/videos/challenges/129-koch-fractal-snowflake/index.json
- content/videos/challenges/136-polar-noise-loops/index.json
117-seven-segment add related challenges, link from yt-desc
120-bit-shifting, 136-polar noise loops  add timestamp to livestream link
127 brownian snowflake -add related challenges and link to livestream archive
128 sketchRNN snowflake add link to livestream archive
129 - koch snowflake fix typo, add link to livestream archive
> Add related challenges, fix typos, add/edit link to livestream archive

- content/pages/homepage/index.json
- content/videos/challenges/c2-collatz-conjecture/showcase/contribution13.json
- content/videos/challenges/c2-collatz-conjecture/showcase/contribution4.json
- content/videos/challenges/c3-hilbert-curve/showcase/contribution14.json
- content/videos/challenges/c3-hilbert-curve/showcase/contribution16.json
- content/videos/challenges/c3-hilbert-curve/showcase/contribution4.json
- content/videos/challenges/c4-worley-noise/index.json
- content/videos/challenges/c4-worley-noise/showcase/contribution14.json
- content/videos/challenges/c5-marching-squares/showcase/contribution11.json
- content/videos/challenges/c5-marching-squares/showcase/contribution5.json
- content/videos/challenges/c5-marching-squares/showcase/contribution7.json
- content/videos/challenges/c5-marching-squares/showcase/contribution9.json
Updating homepage 11/7 and eliminating filler in showcase jsons.
> Updating featured challenges/showcases 

- content-testing/file-formats.js
- netlify/functions/submission-background.js
- src/components/PassengerShowcaseForm.js
Working on #501 (should probably be combined with #512)
> Adding Social Media Handles to Passenger Showcase Form

- src/components/ShareButton.js
- src/components/ShareButton.module.css
- src/components/Tabs.js
This solves the issue in issue #772.
> fixed position of alert box

- gatsby-node.js
- node-scripts/page-generation.js
- node-scripts/schema.js
- src/templates/challenges.js
- src/templates/tracks.js
For example, the `A* algorithm` topic should return a result but doesn't: https://thecodingtrain.com/challenges/lang/all/topic/a*-algorithm
Preview build: https://deploy-preview-808--codingtrain.netlify.app/challenges/lang/all/topic/a*-algorithm
> Fix tracks and challenges filtering for tags containing special regex characters

- src/components/PassengerShowcaseForm.js
This PR reverts the previous PR which causes the showcase submission to give an error, (even though the showcase gets submitted)
> Revert: showcase PR url preview

- src/components/LinkList.module.css
Hi, I modified the url class in `--reduced` size in the `LinkList.module.css`. I opened the website in development mode and that seems to have fixed the problem.
> Modified the url class in `--reduced` size in the `LinkList.module.css` file

- src/components/LinkList.module.css
Fix link overflow on the right side
Referring to this comment: https://github.com/CodingTrain/thecodingtrain.com/pull/831#issuecomment-1356137680
Should fix #798
> Fix link overflow on the right

- static/thankyou/sketch.js
- static/thankyou/supporterDatabase.json
> Initial round of whistle numbers

- netlify/functions/submission-background.js
- package-lock.json
- package.json
This should fix the encoding issue we've observed in #928
> Replace `btoa` with native Buffer base64 encoding

- content/tracks/main-tracks/the-nature-of-code-2/index.json
Add simple pendulum and spring forces to NOC track
> Update NOC track

- src/components/PassengerShowcasePanel.js
Removing the word "contribution" as much as possible (see #404).
> Minor showcase language edits

- content/videos/challenges/156-peeking-inside-pi/showcase/contribution5.json
The deployment URL for coding challenge #156 - Peeking inside Pi has been updated. Updating the new link in the contribution file.
> Update contribution deployment URL.

- content/videos/challenges/108-barnsley-fern/index.json
- content/videos/challenges/14-fractal-trees-recursive/index.json
- content/videos/challenges/15-object-oriented-fractal-trees/index.json
- content/videos/challenges/16-l-system-fractal-trees/index.json
- content/videos/challenges/17-fractal-trees-space-colonization/index.json
- content/videos/challenges/18-3d-fractal-trees/index.json
- content/videos/challenges/21-mandelbrot-set-with-p5js/index.json
- content/videos/challenges/22-julia-set/index.json
- content/videos/challenges/34-diffusion-limited-aggregation/index.json
- content/videos/challenges/61-fractal-spirograph/index.json
- content/videos/challenges/65-binary-tree/index.json
I'm working on Nature of Code chapter 8 so making some small adjustment to the related challenges.
> Minor "topics" cleanup related to fractals and trees

- content/videos/challenges/108-barnsley-fern/index.json
- content/videos/challenges/129-koch-fractal-snowflake/index.json
- content/videos/challenges/14-fractal-trees-recursive/index.json
- content/videos/challenges/15-object-oriented-fractal-trees/index.json
- content/videos/challenges/16-l-system-fractal-trees/index.json
- content/videos/challenges/168-the-mandelbulb/index.json
- content/videos/challenges/17-fractal-trees-space-colonization/index.json
- content/videos/challenges/18-3d-fractal-trees/index.json
- content/videos/challenges/21-mandelbrot-set-with-p5js/index.json
- content/videos/challenges/22-julia-set/index.json
- content/videos/challenges/34-diffusion-limited-aggregation/index.json
- content/videos/challenges/61-fractal-spirograph/index.json
- content/videos/challenges/77-recursion/index.json
I think I got everything related to "fractal" now!
> More topics cleanup

- node-scripts/tags-transforms.json
Thanks to suggestion from @fturmel #987
> Fractal Tag Transform

- content/videos/challenges/148-gift-wrapping/index.json
- content/videos/challenges/157-zoom-annotations/index.json
- content/videos/challenges/164-slitscan/index.json
- content/videos/challenges/166-image-to-ascii/index.json
- content/videos/challenges/167-prime-spiral/index.json
- content/videos/challenges/170-monty-hall-problem/index.json
- content/videos/challenges/171-wave-function-collapse/index.json
- content/videos/challenges/172-directional-boring/index.json
- content/videos/challenges/56-attraction-and-repulsion-forces/index.json
- content/videos/challenges/67-pong/index.json
- content/videos/challenges/c2-collatz-conjecture/index.json
I have update the  related challenges for 56, 67, 148, 157, 164, 166, 167, 170, 171, 172, c2.
> Add related challenges  re Issue #1005

- content/videos/challenges/178-climate-spiral/index.json
- package.json
- Fixed some info in `index.json`
- Added a `formatc` script to `package.json` to format all content files
*** 
In the `Files Changed` tab, the diff viewer by default shows quite a lot of changes due to linting. To view the actual changes to files, check the `Hide Whitespace` box under the gear icon, and click on `Apply and reload`.
> Climate Spiral content fixes

- netlify/functions/submission-background.js
Add newline to generated showcase json, to align with linter rules
> Add newline to showcase json

- content/pages/challenges/index.json
- content/pages/homepage/index.json
update featured challenges and showcases
> update index.json files

- src/components/ItemsPage.js
- src/templates/showcases.js
Update CTA text on showcase page to "Add Yours!" | "Submit" and links to passenger showcase guide/form
Closes #974
> Showcase Page - Update CTA

- content/videos/challenges/117-seven-segment-display/showcase/contribution15.json
- content/videos/challenges/121-logo-interpreter/showcase/contribution1.json
- content/videos/challenges/124-flocking-simulation/showcase/contribution15.json
- content/videos/challenges/124-flocking-simulation/showcase/contribution4.json
- content/videos/challenges/129-koch-fractal-snowflake/showcase/contribution3.json
- content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution1.json
- content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution2.json
- content/videos/challenges/134-heart-curve/showcase/contribution1.json
- content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution4.json
- content/videos/challenges/14-fractal-trees-recursive/showcase/contribution5.json
- content/videos/challenges/140-pi-leibniz/showcase/contribution4.json
- content/videos/challenges/144-2d-black-hole-visualization/showcase/contribution2.json
- content/videos/challenges/145-ray-casting-2d/showcase/contribution10.json
- content/videos/challenges/146-rendering-ray-casting/showcase/contribution2.json
- content/videos/challenges/16-l-system-fractal-trees/showcase/contribution1.json
- content/videos/challenges/27-fireworks/showcase/contribution3.json
- content/videos/challenges/3-snake-game/showcase/contribution30.json
- content/videos/challenges/36-blobby/showcase/contribution1.json
- content/videos/challenges/46-asteroids/showcase/contribution2.json
- content/videos/challenges/50-animated-circle-packing/showcase/contribution2.json
- content/videos/challenges/51-a-pathfinding-algorithm/showcase/contribution5.json
- content/videos/challenges/59-steering-behaviors/showcase/contribution6.json
- content/videos/challenges/64-kinematics/showcase/contribution1.json
- content/videos/challenges/65-binary-tree/showcase/contribution6.json
- content/videos/challenges/76-10Print/showcase/contribution8.json
- content/videos/challenges/78-simple-particle-system/showcase/contribution9.json
- content/videos/challenges/85-the-game-of-life/showcase/contribution13.json
- content/videos/challenges/93-double-pendulum/showcase/contribution2.json
- content/videos/challenges/c2-collatz-conjecture/showcase/contribution9.json
- content/videos/ml5/6-train-your-own-neural-network/1-train-the-model/showcase/contribution3.json
Trying yet again - maybe the GitHub actions/UI glitches are resolved
> Fix contributions urls (3rd attempt)

- content/pages/challenges/index.json
Change to c2-collatz-conjecture
> Update featured challenge

- content/tracks/main-tracks/ml5js-beginners-guide/index.json
- content/videos/ml5/1-classification/1-image-classification/index.json
- content/videos/ml5/1-classification/2-webcam-classification/index.json
- content/videos/ml5/1-classification/3-object-detection/index.json
- content/videos/ml5/10-sound-classification/1-sound-classification/index.json
- content/videos/ml5/2-transfer-learning/1-transfer-learning/index.json
- content/videos/ml5/3-feature-extractor/1-classification/index.json
- content/videos/ml5/3-feature-extractor/2-regression/index.json
- content/videos/ml5/4-save-and-load-model/1-save-load-model/index.json
- content/videos/ml5/5-knn-classification/1-build-the-image-classifier/index.json
- content/videos/ml5/5-knn-classification/2-train-the-model/index.json
- content/videos/ml5/5-knn-classification/3-save-and-load-model/index.json
- content/videos/ml5/6-train-your-own-neural-network/1-train-the-model/index.json
- content/videos/ml5/6-train-your-own-neural-network/2-save-data/index.json
- content/videos/ml5/6-train-your-own-neural-network/3-save-model/index.json
- content/videos/ml5/6-train-your-own-neural-network/4-regression/index.json
- content/videos/ml5/7-posenet/1-finding-keypoints/index.json
- content/videos/ml5/7-posenet/2-pose-classifier/index.json
- content/videos/ml5/7-posenet/3-pose-regression/index.json
- content/videos/ml5/8-convolutional-neural-network/1-pixels-as-input/index.json
- content/videos/ml5/8-convolutional-neural-network/2-architecture-of-cnn/index.json
- content/videos/ml5/8-convolutional-neural-network/3-max-pooling/index.json
- content/videos/ml5/8-convolutional-neural-network/4-image-classification/index.json
- content/videos/ml5/9-doodleNet/1-doodleNet/index.json
I think I have removed  "ml5.js" from all of the files.  (This is a  branch off of the original pull request.)
> Remove ml5.js from ml5 video titles

- content/tracks/main-tracks/ml5js-beginners-guide/index.json
- content/videos/ml5/10-sound-classification/1-sound-classification/index.json
I have also  added the 147-chrome dinosaur challenge to the track.
> Add sound classifier video to ml5 track.

- content/videos/challenges/14-fractal-trees-recursive/index.json
> Fix small typo in description of 14-Fractal-trees

- content/videos/challenges/176-buffon-needle/index.json
- content/videos/challenges/36-blobby/index.json
- content/videos/data/3-the-weather-here/5-web-application-deployment/index.json
- content/videos/more-p5/local-storage/index.json
- content/videos/noc/9-genetic-algorithms/2-how-it-works/index.json
- content/videos/noc/9-genetic-algorithms/6-improved-fitness-function/index.json
- content/videos/open-simplex-noise/index.json
- content/videos/webgl/1-introduction/index.json
- content/videos/webgl/2-3d-geometries/index.json
- content/videos/webgl/3-light-and-material/index.json
- content/videos/webgl/4-texture/index.json
- content/videos/webgl/5-camera-and-perspective/index.json
- content/videos/webgl/6-createGraphics/index.json
- content/videos/webgl/7-loading-an-obj-file/index.json
- content/videos/webgl/8-3d-custom-shapes/index.json
Correcting small mistakes, capitalization, etc.
> Misc topics and languages corrections

- static/_redirects
Add a redirect as suggested in https://github.com/CodingTrain/thecodingtrain.com/issues/1127
https://deploy-preview-1138--codingtrain.netlify.app/submit now redirects to https://deploy-preview-1138--codingtrain.netlify.app/guides/passenger-showcase-guide
> Redirect /submit to /guides/passenger-showcase-guide

- src/components/CodeExampleList.js
- src/components/CreditList.js
- src/components/LinkList.js
- src/components/Tags.js
- src/components/TimestampTimeline.js
- src/components/challenges/PartsTimeline.js
- src/components/tracks/OverviewTimeline.js
This is a very minor cleanup around the usage of React `memo()`. It removes a few duplicate calls and tries to be more consistent with its usage by applying the memoization along with the `export` statement when possible.
> Cleanup `memo` usage

- src/components/PassengerShowcaseForm.js
🚂 [Deploy Preview](https://deploy-preview-1163--codingtrain.netlify.app/guides/passenger-showcase-guide)
Groups videos according to chapters
Normal tracks work as usual
<sub>(I don't think this is as important but thought that it would be cool to have)</sub>
> [Showcase Form] Group track videos into chapters

- contribution1-mehak-shapes/showcase-contibitution
Adding my first showcase edition and also my first code .
> Create showcase-contibitution - shapes and line

- content/videos/challenges/140-pi-leibniz/index.json
- content/videos/challenges/141-mandelbrot-pi/index.json
- content/videos/challenges/176-buffon-needle/index.json
- content/videos/challenges/95-approximating-the-value-of-pi/index.json
- content/videos/challenges/96-visualizing-digits-of-pi/index.json
I was searching for my Pi approximation videos all together and noticed some inconsistencies in the topics for these videos. This should clean things up a bit.
> Pi Day videos topics

- src/components/tracks/Card.js
- src/components/tracks/Header.js
- src/pages/index.js
New edge case since tracks always contained multiple videos until #1214
> Don't pluralize video count label for tracks with only one video

- content/videos/challenges/102-2d-water-ripple/index.json
- content/videos/challenges/103-fire-effect/index.json
- content/videos/challenges/132-fluid-simulation/index.json
- content/videos/challenges/47-pixel-sorting-in-processing/index.json
- content/videos/challenges/49-photo-mosaic-with-white-house-social-media-images/index.json
- content/videos/challenges/50-animated-circle-packing/index.json
- content/videos/pixels/brightness-mirror/index.json
- content/videos/pixels/checkbox-mirror/index.json
- content/videos/pixels/createCapture/index.json
- content/videos/pixels/painting-with-pixels/index.json
- content/videos/pixels/video-photobooth/index.json
Continuing to organize videos and challenges related to the pixel array, would welcome any feedback and contributions!
> Cleaning up Pixels Topics

- static/_redirects
Now going to:
https://discord.com/servers/coding-train-choo-choo-276096133695143936
> Update Discord Redirect

- node-scripts/yt-description.mjs
(#1311) fix yt-desc showing all code examples
> show all code examples (other than p5 and github)

- content/videos/challenges/54-islamic-star-patterns/index.json
This is the paper referenced in the video which was published more recently, we could include both but this is the one I look at more specifically in the video.
> Updating Star Patterns paper to 2005

- content/pages/challenges/index.json
- content/pages/homepage/index.json
- content/videos/challenges/102-2d-water-ripple/index.json
- content/videos/challenges/107-sandpiles/index.json
- content/videos/challenges/119-binary-to-decimal-conversion/index.json
- content/videos/challenges/13-reaction-diffusion/index.json
- content/videos/challenges/180-falling-sand/index.json
- content/videos/challenges/85-the-game-of-life/index.json
- content/videos/challenges/89-langtons-ant/index.json
- content/videos/pixels/painting-with-pixels/index.json
@kfahn22 Feel free to use this branch if you have things to update / change! I need to remember to add this new challenge as related to other videos!
> Minor edits to falling sand page

- content/videos/challenges/180-falling-sand/showcase/contribution-1706412654.json
New version with 'pixelDensity(1)' fixing the canvas for retina display.
> Fixed retina displays contribution-1706412654.json

- content/pages/homepage/index.json
Update showcases and challenges
> Update homepage 2-9-24

- content/videos/challenges/182-apollonian-gasket/showcase/contribution-1710472424.json
Just fixing a typo! I wrote "Colofur" instead of "Colorful" :)
Thanks!
> Update contribution-1710472424.json fixed typo

- static/_redirects
Text for upcoming instagram post:
All aboard for the first highlight of the #PassengerShowcase! Coding Challenge 179: Cellular Automata. 🎉🥳 
Watch the full video of this challenge at [codingtrain.com/ca](http://codingtrain.com/ca) 🎥 
📣 Get your ticket to be featured in next week’s #PassengerShowcase post by submitting your work via one of the following methods:
1. WEBSITE: Navigate to [codingtrain.com/submit](http://codingtrain.com/submit) 🧑‍💻
2. INSTAGRAM: Post & use the hashtag #PassengerShowcase 🚂
3. DISCORD: Join us at [codingtrain.com/discord](http://codingtrain.com/discord) #share channel 💬
We are so thrilled to celebrate the community’s talent and creativity. 😆🌟
#CodingTrain #CreativeCoding #Processing #p5.js
> alias for wolfram CA

- content/pages/about/index.json
> Acknowledgements Updates

- src/components/PassengerShowcaseForm.module.css
> Fix: Dark Mode - Passenger Showcase Form broken (Windows) 

- content/videos/challenges/181-image-stippling/showcase/contribution-1718452344.json
Closes #1624
Updated the URL to link to demo, per author request.
> Fix contribution url

- HACKTOBERFEST.md
I have removed the the logo edits and making changes to other Coding Train repos.
> Edit Hacktoberfest.md

- static/_redirects
Creating a redirect for the halloween example!
> Halloween Example

- content/videos/ml5/facemesh/index.json
In preparing for my NYU class I noticed this example was linked incorrectly
> correcting facemesh 3D

- content/videos/livestreams/p5js-2.0/index.json
- multilingual and typography curation
- #WCCC curation
> Additional links for p5-2-live
