content/pages/homepage/index.json

Updates the homepage to include:

Adding PCD Copenhagen event

---

content/pages/guides/mantain-website-guide.md

- update hierarchy of `ex-contributor guide` to `h2` instead of `h1` ensure that all page headings are on the same level and the table of contents will now display multiple sections(that all have `h2`) instead of `ex-contributor guide` which has a higher hierarchy than the rest. 
- Update page to ensure that page formatting continues to work after the jekyll command. I added a `<br/>` and removed an extra backtick. I thought the space was necessary to ensure that the jekyll command appeared distinct from the code snippet right above it.
| Before  |  After |
|---|---|
| Before (Table of Contents only contains 1 item): <img width="1572" alt="Screen Shot 2022-06-04 at 3 32 48 PM" src="https://user-images.githubusercontent.com/6998954/172023131-a51038ff-8580-4f19-9b40-80e873a9f312.png">  | …

Address Formatting Issues in "Maintaining the Website" Guide

---

content/pages/guides/mantain-website-guide.md

- This pull request addresses https://github.com/CodingTrain/thecodingtrain.com/issues/148 in order to add some instructions to help folks figure out how to add upcoming events to The Coding Train Website.
- I tried to model the documentation based off of the other information available in the guide. I wasn't sure where this instruction should fit in the hierarchy of the guide.

Create a section in "Maintaining the Website" Guide to address adding events

---

content-testing/content-structure.js

Little fix to [comment](https://github.com/CodingTrain/thecodingtrain.com/issues/44#issuecomment-1146672822) that allows subfolders in `content/pages/guides`, and also `content/pages/about` because it seemed appropriate.

fix: allows subfolders inside of guides and about content folders

---

src/templates/guide.module.css

I noticed in the new guides a little style bug, lists get a left border, even when they are nested:
This PR fixes that:

fix: sublists don't have left border

---

content/pages/guides/mantain-website-guide.md

- Added a "Linking Code Examples" section in the Website Maintainence Guide.
If you feel that something is missing and/or something else needs to be added here, please let me know.
(do you think changes from the earlier system of `CodingTrain/website` needs to be mentioned?)

Add 'Linking Code Examples' in Site Maintanence Guide

---

gatsby-config.js
src/components/Head.js
src/components/ItemsPage.js
src/components/Layout.js
src/pages/404.js
src/pages/about.js
src/pages/guides.js
src/templates/challenge.js
src/templates/challenges.js
src/templates/guide.js
src/templates/track-video.js
src/templates/tracks.js

This completes the metadata settings initially set for the site, and also adds images to the setup as proposed in #170.
The approach is taking both text and image content already worked on for every site and using it as metadata for each page.
For example, for titles and descriptions, which most pages have, this are also injected as metadata for the corresponding page. So tracks titles and descriptions get injected in the first video page of each track, and each individual video page also has their own title and description metadata.
Images would work the same way. I'll show here how each preview looks, and indicate where is the image taken from. Some images probably will need to be replaced, since some are still placeholders from a while ago.
Also a little note: Because the meta tags …

Meta images

---

content/videos/challenges/19-superellipse/index.json

Fixed link name for the Supershapes website
Apparently, even in the [old website](https://codingtrain.github.io/website-archive/CodingChallenges/019-superellipse.html) the supershapes link was named "space colonization algorithm"

Fix link title 

---

src/components/PassengerShowcasePanel.js

In many Passenger Showcase contributions, the names are long and are cut off.
This PR adds a tooltip which shows the full name of the contribution on hovering on its header. This is only applied to names longer than 30 characters long.
(Here, I am hovering on the contribution header. The mouse is not visible in screenshots.)

Add tooltip to Contribution header for long names

---

content/pages/guides/maintain-website-guide.md

Should be merged only after PR #428 is merged into the main branch.
This adds documentation on the "Maintaining the website" guide regarding multi-part challenges.
https://deploy-preview-465--codingtrain.netlify.app/guides/maintain-website-guide

Documentation for porting multi-part Coding Challenges

---

content-testing/content-structure.js
content-testing/file-formats.js
content-testing/slug-references.js
content/tracks/index.json
node-scripts/node-generation.js
node-scripts/schema.js
src/templates/tracks.js

As proposed in #417, this adds the loading of an JSON file that defined the order in which tracks are shown in the Track Page. The file should be located in `content/tracks/index.json`, and should be an object with a `"trackOrder"` property that is an array of slug strings for the tracks. If a track is not found in this array, it will get assigned a very high number.
This also adds the front-end graphql query, and tests for this new file.

feat: adds ability to sort tracks in track page

---

content/videos/challenges/173-snake-applesoft-basic/index.json

Fixed typo in AppleSoft BASIC manual description ("originan" -> "original").

Fixed typo

---

src/templates/track-video.js

This PR resolves #514.
- Use track cover image for share preview
- Prioritizes `index.png` for video over track thumbnail

Add track cover image as share preview

---

node-scripts/yt-description.js

* Parses multipart challenges and creates separate file for each part
* Changed output filename `{videoId}.txt`
Test:
```
npm run yt-desc challenges/35-traveling-salesperson
```
The filename change is required because otherwise all parts will be written into the same file. However, this might be a problem when this script is being used for new challenges for which `videoId` is not created yet. What should be the filename for the output files?

YT Desc: Add Support for Multipart Challenges 

---

node-scripts/yt-description.js

Based on comments by @shiffman on https://github.com/CodingTrain/thecodingtrain.com/issues/205#issuecomment-1236461778
Merge after #537
- Changes script CLI to use the website URL instead of file path.
- Add `Code:` before website url in description
❗Note: For videos in multiple tracks, only one URL will work (usually, the directory in which its metadata is present).
```
Coding Train YouTube Description Generator
Usage:
All Videos: npm run yt-desc
Specific Video: npm run yt-desc <coding-train-website-url>
example:
npm run yt-desc https://thecodingtrain.com/challenges/171-wave-function-collapse
Output files are saved to `./_descriptions` directory
```

yt-desc: Use website URL as input

---

content/videos/code/3-conditionals/4-boolean/index.json
content/videos/code/6-objects/2-classes/index.json
content/videos/code/6-objects/3-constructor/index.json

Fixing typos in the timestamps for two videos and adding 2 links that were in the description in 6.3.

Code! fixing typos and adding links

---

content/videos/challenges/162-self-avoiding-walk/index.json
content/videos/challenges/52-random-walker/index.json
content/videos/challenges/53-random-walker-with-vectors-and-levy-flight/index.json

These are the links I suggest : 
| Challenge | Related Challenges |
|---|---|
| 52-random-walker |  53-random-walker-with-vectors-and-levy-flight, 162-self-avoiding-walk |
| 53-random-walker-with-vectors-and-levy-flight | 52-random-walker,  162-self-avoiding-walk |
| 162-self-avoiding-walk | 52-random-walker, 10-dfs-maze-generator |
I also replaced YouTube video links with links to the corresponding challenge pages on the website
Affected pages preview : 
- https://deploy-preview-568--codingtrain.netlify.app/challenges/52-random-walker
- https://deploy-preview-568--codingtrain.netlify.app/challenges/53-random-walker-with-vectors-and-levy-flight
- https://deploy-preview-568--codingtrain.netlify.app/challenges/162-self-avoiding-walk

Adding "relatedChallenges" to Random Walk related challenges

---

content/videos/challenges/162-self-avoiding-walk/index.json
src/components/ChallengesPanel.js
src/components/ChallengesPanel.module.css
src/templates/challenge.js
src/utils/index.js

Hi! The "Try a Challenge!" section on a challenge page only shows the first 2 challenges from the "relatedChallenges" array. So putting more than 2 challenges in this array seems kind of odd. Unless we randomize the challenges that are shown on the page.
So this is my suggestion :smile:  I don't know if that's a good idea. One drawback of this is that this doesn't seem to work great with SSG (Static Site Generation).
Preview example : https://deploy-preview-572--codingtrain.netlify.app/challenges/162-self-avoiding-walk

Suggestion : Randomized related challenges view

---

content-testing/file-formats.js
content/templates/showcase/contribution1.json
content/templates/videos/contribution1.json
netlify/functions/submission-background.js

Added field `submittedOn` to showcase submissions, as proposed in https://github.com/CodingTrain/thecodingtrain.com/issues/569#issuecomment-1256380913.
This field contains only the date (not time) of execution of the `submission-background` netlify function.
Let me know if any changes are required!

Add submittedOn field to showcase contributions

---

content/pages/homepage/index.json
src/pages/index.js
src/styles/pages/index.module.css

Hi! :steam_locomotive:  This PR implements a part of issue #590. It's a rework on the Passenger Showcase Highlight section on the Homepage. The goal is to display three contributions instead of one.
The simplest way to stack 3 contributions woud be to do this :
I worked a bit more on this design so that it fits better with the rest of the page : 
1. I used a bigger font-size for the "PASSENGER SHOWCASE HIGHLIGHT" title do that it fits better with the rest of the titles on the Homepage ;
2. I replaced the three "READY TO BE INSPIRED?" banners with only one at the top to avoid duplication and to avoid having three big CTA buttons at the same place ;
3. I added hierarchy on the details of the contribution by playing with the font sizes and colors : I emphasized the title of the contribution, …

Multiple Featured Showcase on the Homepage

---

src/styles/pages/index.module.css

Hi :steam_locomotive: I just noticed some overflow on the title of passenger showcases on the homepage (PR #665). Here's a fix :
Wide screen (before)
Wide screen (after)
Medium screen (before)
Medium screen (after)
Small screen (before)
Small screen (after)

Fix height of passenger showcase details on homepage

---

content/videos/challenges/104-linear-regression-with-tensorflowjs/index.json
content/videos/challenges/26-3d-supershapes/index.json
content/videos/challenges/3-snake-game/index.json
content/videos/challenges/30-phyllotaxis/index.json
content/videos/challenges/32-agario/index.json
content/videos/challenges/35-traveling-salesperson/index.json
content/videos/challenges/39-madlibs-generator/index.json
content/videos/challenges/42-markov-chain-name-generator/index.json
content/videos/challenges/62-plinko-with-matterjs/index.json
content/videos/challenges/68-breadth-first-search/index.json
content/videos/challenges/69-evolutionary-steering-behaviors/index.json
content/videos/challenges/70-nearest-neighbors-recommendation-engine/index.json
content/videos/challenges/77-recursion/index.json
content/videos/challenges/78-simple-particle-system/index.json
content/videos/challenges/81-circle-morphing/index.json
content/videos/challenges/91-snakes-and-ladders/index.json

Adding Live Stream archive links:  35, 62, 68, 69, 77, 78, 91
Adding relatedChallenges to 3, 39,42,70,91
104 - both livestream archive link and related challenge 
26- fix typo
81- Add link to Golan Levin's repo that was in yt-desc and missing from json
30- remove duplicate link
32 - add link to collaborative sketches playlist in yt-desc
3- updated json (moved moved ported challenge from videos to related challenges

Adding links to livestream archive  and adding more  related challenges 

---

src/components/LinkList.js

Resolves #725 
(The tooltip is only applied to titles longer than 30 characters.)
Preview Links:
- https://deploy-preview-734--codingtrain.netlify.app/challenges/133-time-tables-cardioid-visualization
- https://deploy-preview-734--codingtrain.netlify.app/challenges/151-ukulele-tuner-with-machine-learning

Add tooltip for long link titles

---

node-scripts/yt-description.js

Noticed the challenge numbers were causing this issue ⬆️

Remove # from YT description

---

content/videos/challenges/153-interactive-drawing-with-sketchrnn/index.json
content/videos/ml5/0-introduction/1-introduction/index.json
content/videos/ml5/1-classification/1-image-classification/index.json
content/videos/ml5/2-transfer-learning/1-transfer-learning/index.json
content/videos/ml5/7-posenet/2-pose-classifier/index.json
content/videos/ml5/8-convolutional-neural-network/2-architecture-of-cnn/index.json
gatsby-config.js
gatsby-node.js
node-scripts/node-generation.js
node-scripts/page-generation.js
node-scripts/schema.js
package-lock.json
package.json
src/components/ItemsPage.js
src/templates/challenges.js
src/templates/tracks.js

Hi @shiffman & team!
I was watching the [stream on YouTube](https://youtu.be/EzYDNydDUfc?t=2391) last Friday and was intrigued by the Gatsby/GraphQL/Netlify log warnings and slow builds. Thought it would be a fun challenge to learn a bit more about these and see if I could help out.
The slowness comes from building the tracks and challenges pages with all filter permutations and pagination. It ends up being a lot of pages!
Here's what I did:
- **Make some of the async code run serially**. There are just too many things running at once, and it ends up making performance worst. This was enough to get rid of the flood of warnings in the logs.
- **Rewrote some GraphQL queries** to make them a bit faster
- **Build contextual languages and topics lists to reduce total permutations and improve …

Build performance improvements

---

netlify/functions/submission-background.js
src/components/PassengerShowcaseForm.js

This PR reverts all changes in #805.
In #805, the github PR link was added on showcase submission, which allowed the contributor to go to the respective pull request for their showcase. However, it introduced an error due to which an error message was displayed upon submission, even though the showcase was being submitted and the pull request was being created. (initially found by @kfahn22)
I created and merged #822, where I removed the code which caused the bug to temporarily fix the issue.
As it turns out, the problem is that the showcase submission script is a Netlify Background function, and it is not possible to return any data from a background function to the client, thus preventing the client to receive the github PR number, which was being used to display its link to the …

Revert #805 (showcase PR preview URL)

---

src/components/ItemsPage.js
src/components/Select.js
src/components/TopBar.js

Some additional improvements to build/deploy performance.
It's been bothering me that the Netlify build often needs to redeploy thousands of files for no apparent reason after merging PRs that often don't change much. I've been diffing build outputs to understand why.
- the `react-select` component library increments element ids internally by default. This is causing a problem because Gatsby builds using parallel worker threads that execute in an unpredictable order, so a page will very likely end up with a different select component id between each build. Explicitly setting the `instanceId` prop fixes the problem.
https://github.com/JedWatson/react-select/blob/c350a124f8de853a79e0158578d438a35e67e63e/packages/react-select/src/Select.tsx#L638-L639
- the `TopBar` component that displays …

Stabilize HTML build outputs

---

README.md
netlify.toml

This PR updates netlify.toml for Netlify's build CI to ignore file changes to allcontributors and README.
**Testing**
Locally I tested this by running `"git diff --quiet HEAD^ HEAD ':(exclude)README.md' ':(exclude).all-contributorsrc' "`  with and without changes to the relevant files and confirming that it returned a diff when those files changed.  I also pushed multiple commits to this remote branch and looked at the deploy logs to determine whether or not Netlify successfully built or cancelled the build based on the files that were part of the diff for the latest commit.
Netlify build detects the ignore command and continued building this PR when there were changes to `netlify.toml` 
Netlify cancelled build when the only changes in the PR were to`README.md` 
Note: The last build is …

Skip Netlify Preview Build for changes to README + .allcontributors

---

gatsby-node.js
node-scripts/node-generation.js
node-scripts/schema.js

Because of the way the Gatsby nodes were modeled, adding a new showcase would not be detected by the build until the parent challenge or track video JSON would be modified.
You can clearly see the problem in yesterday's showcase PR #841
The incremental build did not detect any changes and the contributor's content is not in the preview link - nor is it right now in production after merge: https://app.netlify.com/sites/codingtrain/deploys/63a010ca0cc5690009e46d9e

Fix Gatsby build cache not detecting new showcases

---

content/videos/challenges/154-tic-tac-toe-minimax/showcase/contribution-1669289438.json
content/videos/challenges/67-pong/showcase/contribution-1665085801.json

There was something wrong with the character encoding in these JSON files.

Fix character encoding for two showcase contributor names

---

gatsby-node.js
node-scripts/page-generation.js
src/components/Layout.js

I converted the `TopBar` and `Footer` component to use [Gatsby 5 slices](https://www.gatsbyjs.com/docs/how-to/performance/using-slices/). I'm not convinced we'll see a significant impact to build times here because that's not where the heavy lifting happens, but it can't hurt.
Eventually we could find other opportunities to use slices that could move the needle a bit more. For example, I was thinking the top part of the challenges page could be a good one to isolate and put in a slice because it's the same for at least 6k pages. And each content card will also appear in a lot of pages because of the filters and pagination, they can each be their own slice.

`TopBar` and `Footer` component to Gatsby slices

---

netlify/functions/submission-background.js
package-lock.json
package.json
src/components/PassengerShowcaseForm.js

Per recent attempts to upload backdoors/malware through the Passenger submission form, this is using the Sharp library to parse the submitted file in the lambda function and make sure it's an actual PNG or JPEG.
Based on the detected image format, it can determine the correct file extension to use, so we don't need `imageExt` anymore.
I also moved the GitHub token check up so it happens before it is passed to Octokit.
@shiffman @dipamsen Let me know what you think! I tested locally, but it should be possible to test it with the Netlify preview link. I didn't want to create test PRs that I couldn't delete myself.

Add image validation to passenger submission lambda

---

src/pages/index.js
src/templates/guide.js

- Added missing `id` in homepage to make the "passenger showcase" footer anchor link work properly
- Replaced the `kebabCase` function with slugify in guides pages so that anchors work more predictably. It was transforming "GitHub" to "git-hub" for example and broke that specific anchor.

Fix anchors in homepage and guides

---

content/videos/challenges/134-heart-curve/index.json

The link for the beat heart GIF went to the Heart curve sketch.  Fixing that mistake.

Fix link to p5 sketch for beating heart

---

content-testing/files.test.js
content-testing/folders.test.js
package-lock.json
package.json

In my opinion, this dependency is not bringing enough value to justify its use in the project. The few tests that were using extended `expect()` methods were easily rewritten with core ones.
`"bail": 0` in `package.json` could also be removed since it's already the default https://jestjs.io/docs/configuration#bail-number--boolean

remove `jest-extended`

---

content-testing/video-canonical-track.test.js
gatsby-config.mjs
node-scripts/find-large-images.js
node-scripts/tags-transforms.js
node-scripts/yt-description.js
package-lock.json
package.json

This brings all project deps to their latest versions.
As a reminder, we needed Gatsby 5.3 and the `gatsby-config` file to be ESM to be able to upgrade to `remark-gfm` 3.x.
Could be worth migrating the other Gatsby nodejs files to ESM eventually, maybe even every nodejs code in the repo.

Upgrade deps (glob 9.x, remark-gfm 3.x) + gatsby-config ESM

---

node-scripts/yt-description.mjs
package-lock.json
package.json

Added copy to clipboard option to `yt-desc`
```
npm run yt-desc path/to/index.json -- -c
```
(Using `-c` directly doesn't work, because for using `npm run` only passes option args if prepended with `--`.)
Also migrated to ESM because `clipboardy@3` only supports ESM.

Add copy to clipboard in yt-desc (migrate to ESM)

---

node-scripts/yt-description.mjs

This section is only shown if: 
- it is a video from a main track, which contains a `playlistId` field.
- or challenges
This section will be shown for **all videos**. (❗Is this reasonable? Should the default be something else?)
- If the video is a challenge, no change in behaviour
- If the video is from a track which does not have a `playlistId` field, then only `Previous Video` / `Next Video` will be shown (wherever applicable), and not `All Videos`.
- If a video is in multiple tracks, then its `canonicalTrack` will be used.
Now it is possible to give any file path chunk in the generator, and it will know to read all `index.json` files inside the provided directory.
```bash
npm run yt-desc content/videos/transformations/
```
If we generate the descriptions for `transformations`, here are …

yt-desc: Improved Track Parsing and more

---

gatsby-node.js

Closes #1039
The track resolver that locates tags was not using the Challenge nodes correctly.

Fix resolver that finds tags for tracks containing challenges

---

src/components/Tags.js
src/components/Tags.module.css
src/components/tracks/Card.module.css

While we're fixing tags, here are a few adjustments that I had noted down but never spent the time to implement.
- Fix the expand/collapse toggle behavior. The "show less" option was never properly displaying.
- Don't display "show more" when there's only 1 more tag to show. The button itself takes up the space it would've taken to display the remaining tag.
- Don't show the last trailing comma if we have a "show more" button
- Remove padding on the "show more" button so it aligns better when it's first in a row
- Display the amount of tags to be revealed in the "show more" button
The track `ml5js-beginners-guide` illustrates these changes well:
**Before**
https://thecodingtrain.com/tracks/ml5js-beginners-guide
https://user-images.githubusercontent.com/4009209/236052090-fd163510-5665-4d09- …

Minor tags UX improvements

---

node-scripts/node-generation.js

The digest for track Chapter nodes was computed using the `data` variable, which previously had its `videos` property removed.
https://github.com/fturmel/thecodingtrain.com/blob/c2d6f21e5b6ebd64e9c7cbca8d75ab4b285ad44c/node-scripts/node-generation.js#L185C10-L203

fix Gatsby cache problem related to tracks

---

content-testing/format-augmented.test.js

By setting the `abortEarly` option to `false` in the `yup` library and restructuring the unit tests a bit, we can show all schema validation failures (not just the first) and display the Jest errors in a more readable way.
**Before**
**After**

Improve content testing errors

---

package-lock.json
package.json
src/components/Button.js
src/components/Question.js
src/components/ShareButton.js
src/components/ShareButton.module.css
src/components/Tabs.js
src/components/Tabs.module.css
src/components/challenges/VideoSection.js
src/components/challenges/VideoSection.module.css
src/components/tracks/VideoSection.js
src/components/tracks/VideoSection.module.css

A collection of very minor improvements while poking around the site's share button functionality.
- The `ShareButton` implementation looked odd and convoluted to me. I cleaned it up a bit, removed the `copy-to-clipboard` dependency and just used the native Clipboard API which has been [well supported for some time now](https://caniuse.com/async-clipboard).
- Fixed a "copied" [notification position bug](https://github.com/CodingTrain/thecodingtrain.com/issues/772#issuecomment-1335975436) on page load, and also refactored the `Tabs` component so it's a bit more readable and idiomatic (refs over DOM selector).
- Converted a few divs with `role="button"` into actual buttons so that keyboard events don't have to be re-implemented. `onKeyPress` has been …

Refactor ShareButton + minor improvements

---

src/components/Button.js
src/components/ButtonPanel.js
src/components/PassengerShowcaseForm.js
src/components/PassengerShowcasePanel.js
src/templates/challenge.js
src/templates/track-video.js

Had this idea yesterday, works really well!
We're simply passing a state object using the router when the user clicks on one of the "submit to the showcase" CTAs in a track or challenge. This allows the form to know where the user came from and select the correct `track` and `video` values for them.
https://github.com/CodingTrain/thecodingtrain.com/assets/4009209/01e698cf-22dc-4413-82bc-4cb22ff4c73b

Auto-select the track and video submission form fields when possible

---

gatsby/createSchemaCustomization.mjs
src/templates/track-video.js

@dipamsen pointed out on Discord that the Track videos credits were not being displayed, even though they exist (and are required) in the source JSON files. This should fix the issue.

display credits for Track videos

---

static/_redirects

Minor change and addition (I got a note saying the "redirect" wasn't working).
```
/appleii -> /tracks/coding-together-apple-ii
/appleII -> /tracks/coding-together-apple-ii
```

Apple II redirect update

---

HACKTOBERFEST.md

fixes  #1238
The word "guides" was missing in the url.

Fix dead link in HACKTOBERFEST.md

---

content/tracks/side-tracks/physics-libraries/index.json

Closes #1098, I realized no one had actually contributed the proposed change.

add chapters to Physics side track

---

content/videos/processing/index.json

That particular index was missing from the list.
Timecode can be verified here:
https://youtu.be/4JzDttgdILQ?t=2678

adding a time-index for "color" at 44:38

---

content-testing/schemas.js
content-testing/validators.js
content/videos/pixels/painting-with-pixels/index.json
node-scripts/yt-description.mjs

Add correction timestamps within content for outputting in youtube description. The syntax is same as that of normal timestamps, and in the generated description, the corrections are added after the timestamps.
#1252
```json
"corrections": [
{
"time": "02:40",
"title": "This old example is not using classes in JavaScript. Check the accompanying code for an updated version!"
}
],
```
```txt
Corrections: 
02:40 This old example is not using classes in JavaScript. Check the accompanying code for an updated version!
```
--- 
```
npm run yt-desc https://youtu.be/0V3uYA1hafk
```
----
While working on this, I realised an error in the `yt-desc` script, that it only considers one url for each video, whereas in reality there can be multiple urls for a single video on the site.
For example, it does …

Add corrections + enhancement for yt-desc

---

src/templates/challenge.js
src/templates/guide.js
src/templates/track-video.js

Fixed guides metadata image to use guide cover image.
old;
new:
Also commented some info on the different image variables for metadata.

Fix metadata images

---

src/components/challenges/PartsTimeline.js
src/components/challenges/VideoSection.js
src/components/tracks/OverviewTimeline.js
src/components/tracks/VideoSection.js
src/hooks/index.js
src/utils/index.js

Choo choo! :steam_locomotive: 
In response to #1319, I'm giving a go at implementing hash-based navigation between challenge parts. This would allow us to reference a specific challenge part by its URL. Example: https://thecodingtrain.com/challenges/40-word-counter#part-3.
A few observations on my current implementation : 
- `/challenges/40-word-counter` takes us to the 1st part of the challenge
- `/challenges/40-word-counter#part-1` takes us to the 1st part of the challenge
- `/challenges/40-word-counter#part-2` takes us to the 2nd part of the challenge
- `/challenges/40-word-counter#part-3` takes us to the 3rd part of the challenge
Whatever hash value is passed to the URL by the user, the URL is not modified (unless we click on another part link or prev/next button of course) : 
- …

Hash-based challenge parts navigation

---

content/videos/challenges/171-wave-function-collapse/index.json
node-scripts/yt-description.mjs

Fixes #1280 
Old:
New:
Kept `CC###` for the related challenges, because sometimes the challenge titles may not have necessary context (eg. _"What was Coding like 40 years ago?"_)
----
Do these also need to be changed?

Remove redundant video titles from descriptions

---

node-scripts/generate-challenges-redirects.js
package.json
static/_redirects

closes #1553
Some examples:
https://deploy-preview-1556--codingtrain.netlify.app/c2
https://deploy-preview-1556--codingtrain.netlify.app/35
https://deploy-preview-1556--codingtrain.netlify.app/182

Generate challenges redirects/shortcuts at build time

---

src/components/TimestampTimeline.module.css
src/components/challenges/VideoSection.module.css
src/components/tracks/OverviewTimeline.js
src/components/tracks/OverviewTimeline.module.css
src/components/tracks/VideoSection.module.css
src/styles/variables.css

Just a minor change that's been bugging me on the site: the buttons in the timeline section don't have their own individual borders, and the background lines make them confusing while scrolling (pics attached below).
|Before|After|
|:-:|:-:|
|![image](https://github.com/CodingTrain/thecodingtrain.com/assets/49340972/c01dd988-56bf-4dd0-9f71-25646848c135)|![image](https://github.com/CodingTrain/thecodingtrain.com/assets/49340972/8ca2fe3e-acc4-4219-897c-b11ca4203523)|
Yep that's all. Love your content, and happy holidays :D

Change timeline button borders for readability

---

src/templates/guide.module.css

This PR fixes an issue where the table on the "Maintaining the Website Guide" page overflows due to the YouTube URL not wrapping on Chromium-based browsers. The issue was mentioned in [this comment](https://github.com/CodingTrain/thecodingtrain.com/pull/1554#issuecomment-2097954963).
1. Open the "Maintaining the Website Guide" page on a Chromium-based browser (e.g., Google Chrome, DuckDuckGo, Brave) using a desktop or mobile device. [here](https://thecodingtrain.com/guides/maintain-website-guide)
2. Scroll down to the table section.
The table should display correctly, with the YouTube URLs wrapping to the next line if they exceed the table cell width.
On Chromium-based browsers, the YouTube URLs do not wrap, causing the table to overflow horizontally.
| Before | After |
|:------:|:-----:| …

Fix table overflow issue on Chromium browsers

---

src/components/Button.module.css
src/components/PassengerShowcaseForm.js
src/components/PassengerShowcaseForm.module.css

See #1550 
- Adds "waiting" state to showcase form to prevent duplicate submission from double clicks
- Style `disabled` button properly 
cc @fturmel

Add waiting state to showcase form

---

src/components/Head.js

closes #1610
Per the [docs](https://developer.x.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image):
* `twitter:url` is not a thing
* we should be using `name` instead of `property` for the tag keys

Update Twitter/X sharing meta tags

---

CONTRIBUTING.md
HACKTOBERFEST.md
README.md
content-testing/schemas.js
content-testing/validators.js
content/pages/about/index.json
content/pages/faqs/cafe-car.json
content/pages/faqs/find-help.json
content/pages/faqs/livestream-notification.json
content/pages/faqs/suggest-topic.json
content/pages/guides/getting-started.md
content/pages/guides/maintain-website-guide.md
content/pages/guides/passenger-showcase-guide.md
src/components/Footer.js

A few small things I noticed.
* The internal Discord links are now relative
* The 2023 workflow link in the FAQ was wrong
* Misc text and URL updates

Minor URL and copy updates

---

src/components/Select.js

closes #1264
Re-implements the `react-select` default filtering logic to be able to apply better ranked sorting on results. This applies to all instances of the `Select` component (tracks, challenges and showcase pages).
Sort priority:
* Exact match
* Exact word match + how close to start of string the match is
* Partial match + how close to start of string the match is
| Before    | This PR |
| - | - |
| ![CleanShot 2024-07-11 at 12 16 01@2x](https://github.com/CodingTrain/thecodingtrain.com/assets/4009209/b0402a9c-1240-49f5-bff8-9f63e37797da)  | ![CleanShot 2024-07-11 at 12 16 37@2x](https://github.com/CodingTrain/thecodingtrain.com/assets/4009209/b795f388-3597-4fad-b3f6-ccadcafc3da4) |

Improve sort order of `Select` component filtered results

---

src/hooks/index.js
src/utils/index.js

We can remove this passive event listener polyfill thing - I don't think it ever was needed as it was introduced in 2022 (#82) but only exists because of old/dead Edge browser (pre Chromium I assume) from before 2017 and IE 11.
https://caniuse.com/passive-event-listener
I corrected the listeners usage too. The `capture` option is `false` by default, and the `passive` option is not required when removing the listener (it's not even a valid option to begin with).
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#passive
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener#parameters
I also noticed the `randomElement` utility was never used and can be safely removed from the codebase.

Remove passive event "polyfill" and unused `randomElement()` utility

---

content/tracks/main-tracks/the-nature-of-code-2/index.json
content/videos/challenges/184-elastic-collisions/index.json

Also, I don't think the Nature of Code track needs the "2" anymore, ultimately, the Nature of Code is just now this new book and set of videos.

Adding elastic collisions to NOC track

---

content/pages/homepage/index.json

The Nature of Code Book Party!

---

.github/workflows/node.js.yml
.github/workflows/typos.yml
content/videos/archive/ml5/1-finding-keypoints/index.json
content/videos/challenges/105-polynomial-regression-with-tensorflowjs/index.json
content/videos/challenges/118-mastodon-fractal-tree-bot/index.json
content/videos/challenges/184-elastic-collisions/index.json
content/videos/code/7-arrays/4-mouse-interaction/showcase/contribution-1724284721.json
content/videos/ml5/1-classification/3-object-detection/index.json
content/videos/physics-libraries/toxiclibs/1-introduction/index.json
typos.toml

False positives are infrequent enough that I think we could give this a shot. Let me know what you think.
https://github.com/crate-ci/typos

Run `typos` with a GitHub action on PRs
